### ISSUE TITLE
Encrypted

### ISSUE THREAD

**Issue by jandelange** [bizzomate/GoogleChartTimeline-Mendix#1]
Jelle,
Because our customer has sensitive data. Are there possibilities to get the data encrypted data across the line and decrypt it locally.

Jan, for questions 0613708474

**Comment by JelleDekker** [comment]
What do you mean exactly? The Google Timeline Chart is executed locally in the browser, also see: https://developers.google.com/chart/interactive/docs/gallery/timeline#data-policy

**Comment by jandelange** [comment]
Thx, Jelle I didn't see that... 

Met vriendelijke groet,

Jan de Lange
0031 6 13 70 84 74
Op 23-10-2017 08:07:34, Jelle <notifications@github.com> schreef:
What do you mean exactly? The Google Timeline Chart is executed locally in the browser, also see: https://developers.google.com/chart/interactive/docs/gallery/timeline#data-policy [https://developers.google.com/chart/interactive/docs/gallery/timeline#data-policy]
