### ISSUE TITLE
Small issues with the widget

### ISSUE THREAD

**Issue by ADoppenberg** [bizzomate/GoogleChartTimeline-Mendix#4]
Hi Jelle,

The timeline widget is a very helpful and good widget in our project, however we have three small issues/request and we hope that you can help with that. 

First of all when we click on an object the on click microflow is executed. This sets the focus on the clicked attribute but when we click on the same object a second time the on click microflow is not executed. We first need to click on a different object before the first object can be clicked again. Our users are sometimes wondering why they can't click the object and it would help us if the on click microflow is always executed. 

Second of all at a certain width of the widget the times are displayed with a.m. and pm. indication. However we use first of all a dutch language and second of all the English language but for a country which doesn't use the a.m. and pm. indication. We would like this indication removed or maybe have the opportunity to choose a format. 

Third of all, when the time changes to a.m. and p.m. the dates are not visible anymore. This is confusing, because our users are viewing multiple dates and now need to calculate sometime which date some things are on. 

I hope you can help us with these issues. 

Kind regards,
Alwin Doppenberg

**Comment by JelleDekker** [comment]
Hi Alwin,

The first issue you mention I need to look into, that sounds like something from the Mendix/widget side.

The second and third are part of the Google Timeline library itself, it does a lot of things automatically, but this also means you have a little less control over the data presentation. The latest version of the widget allows you to pass on custom options, maybe combined with the info [here](https://developers.google.com/chart/interactive/docs/datesandtimes#formatting-axis-gridline-and-tick-labels) you can get the 24h notation correctly.

**Comment by ADoppenberg** [comment]
Hi Jelle,

Thank you for your quick response and the great help! With your information I have been able to solve the second and third issue. 

Kind regards,
Alwin

**Comment by JelleDekker** [comment]
Hi Alwin,

Just checked it and the problem when clicking the same item for a second time is that Google Charts doesn't have any click handler, it only fires events when the selection changes. Clicking the same item is not a change of selection so the event is not fired a second time by the Google chart (and thus the MF is also not executed).

Best regards,
Jelle
